version: "3.8"
services:
  # Express.jsアプリケーションサービス
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app
      - node_modules:/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb
    command: npm run dev

  # MongoDBサービス
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase

  # Reactフロントエンドサービス
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

# 永続化ボリュームの定義
volumes:
  mongodb_data:
  node_modules:
